### PR TITLE
Added a 5 mm CE marking

### PR DESCRIPTION
**Pull request by rubdos**
Products within scope of the RoHS2 directive must display the CE mark.
The minimum height for the CE mark is 5 mm, hence this footprint.

Example image

(Edit: this is an older version, refer to the bottom of the page please)

Please be careful when using this logo in your design.

I used some tricks to get it [how it should look](http://ec.europa.eu/enterprise/images/ce_mark_big.gif), as the footprints/kicad_mod spec doesn't allow for fills yet afaik.

If someone wants it, I can make larger versions too. I would propose not to add smaller versions, because they are not legal to use when the PCB allows for a larger version.

[An example of its use can be found here](http://gerblook.org/pcb/Q4t9hpWFN4C9th8Whp4knY)

### CODE REVIEW

**Comment by nickoe** [comment]
Your logo does not seem to conform very well with the reference design. For example the lines are too thin.

**Comment by rubdos** [comment]
I updated it to the reference design. It looks acceptable to me now.

comparison

**Comment by nickoe** [comment]
Yes, that looks much better. Now it is time for the library comitters to judge. :+1:

**Comment by rubdos** [comment]
For those interested: [here it's in use on a 40mm*40mm pcb](http://gerblook.org/pcb/FLYmgXmjvNSurK5EbpkaH5)

**Comment by nickoe** [comment]
@CarlPoirier et.al. Are you not on the watchlist for all pretty repos?

**Comment by odurc** [comment]
I think it looks nice. @rubdos, do you like to set the anchor in the middle of the symbols before merge it?

**Comment by rubdos** [comment]
LIke this, @ricardocrudo ? :)

screenshot from 2015-06-27 11 56 36

**Comment by michal777** [comment]
Looks ok, value is bad (should be such as name), I'll fix it. Thanks.

**Comment by nickoe** [comment]
@michal777 I see you did rename it as:

```
-  (fp_text value Symbol_CE_SilkScreen (at 0 3.4) (layer F.Fab) hide
+  (fp_text value Symbol_CE_SilkScreen_small (at 0 3.4) (layer F.Fab) hide
```

Wouldn't it make more sense to write _5mm instead? This will be more specific. Or at least in the description.

**Comment by michal777** [comment]
I haven't rename anything. The convention says the value and footprint name should be equal.

**Comment by nickoe** [comment]
@michal777 Ahh yes, true.  But what do you thing about renaming it to 5mm instead?

**Comment by rubdos** [comment]
To be honest, I didn't check on the size of other `_small` footprints, so I guess _5mm would be more accurate.
Please keep in mind to never supply a CE logo that's smaller, because most of the time, it's illegal to use it. (It's only legal when there is not enough room for something >=5mm)

**Comment by michal777** [comment]
You are right. Renamed.

**Pull request merged**
